apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: <iam-role-arn>
  name: oidc-golang
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-golang
  labels:
    app: oidc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      serviceAccountName: oidc-golang
      containers:
      - name: oidc
        image: wordofprasanna/aws-oidc:latest
        ports:
        - containerPort: 80
        env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "1"
        - name: AWS_REGION
          value: "us-east-1"
